/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    documents: Document;
    authorities: Authority;
    languages: Language;
    language_pairs: LanguagePair;
    price_books: PriceBook;
    use_cases: UseCase;
    regions: Region;
    countries: Country;
    market_profiles: MarketProfile;
    jurisdiction_profiles: JurisdictionProfile;
    administrative_areas: AdministrativeArea;
    faqs: Faq;
    combos: Combo;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    authorities: AuthoritiesSelect<false> | AuthoritiesSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
    language_pairs: LanguagePairsSelect<false> | LanguagePairsSelect<true>;
    price_books: PriceBooksSelect<false> | PriceBooksSelect<true>;
    use_cases: UseCasesSelect<false> | UseCasesSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    market_profiles: MarketProfilesSelect<false> | MarketProfilesSelect<true>;
    jurisdiction_profiles: JurisdictionProfilesSelect<false> | JurisdictionProfilesSelect<true>;
    administrative_areas: AdministrativeAreasSelect<false> | AdministrativeAreasSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    combos: CombosSelect<false> | CombosSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Stable kebab-case identifier.
   */
  key: string;
  status?: ('draft' | 'published') | null;
  tier?: ('0' | '1' | '2') | null;
  slug: {
    ar: string;
    en: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  name: string;
  summary: string;
  body_sections?:
    | {
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  related_services?: (number | Service)[] | null;
  faqs?: (number | Faq)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  key: string;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  topics?:
    | {
        topic?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Stable kebab-case identifier.
   */
  key: string;
  status?: ('draft' | 'published') | null;
  tier?: ('0' | '1' | '2') | null;
  slug: {
    ar: string;
    en: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  name: string;
  category?: ('civil' | 'academic' | 'legal' | 'financial' | 'commercial' | 'medical') | null;
  typical_pages?: number | null;
  requirements?: string | null;
  turnaround_hours?: number | null;
  related_authorities?: (number | Authority)[] | null;
  related_use_cases?: (number | UseCase)[] | null;
  related_documents?: (number | Document)[] | null;
  faqs?: (number | Faq)[] | null;
  combo_flags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authorities".
 */
export interface Authority {
  id: number;
  /**
   * Stable kebab-case identifier.
   */
  key: string;
  status?: ('draft' | 'published') | null;
  tier?: ('0' | '1' | '2') | null;
  slug: {
    ar: string;
    en: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  type: 'embassy' | 'immigration-authority' | 'evaluator' | 'university' | 'court' | 'ministry';
  name: string;
  country?: (number | null) | Country;
  languages?: (number | Language)[] | null;
  requirement_summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  required_language?: (number | null) | Language;
  certification_rule?: string | null;
  legalization_required?: boolean | null;
  last_verified: string;
  source_references: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  top_documents?: (number | Document)[] | null;
  related_use_cases?: (number | UseCase)[] | null;
  faqs?: (number | Faq)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  /**
   * Stable kebab-case identifier.
   */
  key: string;
  status?: ('draft' | 'published') | null;
  tier?: ('0' | '1' | '2') | null;
  slug: {
    ar: string;
    en: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  name: string;
  currency?: string | null;
  timezone?: string | null;
  price_book?: (number | null) | PriceBook;
  legal_notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price_books".
 */
export interface PriceBook {
  id: number;
  key: 'b2c-egypt-egp' | 'b2c-gcc' | 'b2c-tier1-usd';
  currency?: ('EGP' | 'AED' | 'SAR' | 'USD') | null;
  base_pair?: (number | null) | LanguagePair;
  per_page?: number | null;
  minimum_charge?: number | null;
  rush_per_page?: number | null;
  rush_promise_hours?: number | null;
  unit_words_per_page?: number | null;
  pair_overrides?:
    | {
        pair?: (number | null) | LanguagePair;
        per_page?: number | null;
        rush_per_page?: number | null;
        id?: string | null;
      }[]
    | null;
  addons?:
    | {
        label?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  b2b_note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "language_pairs".
 */
export interface LanguagePair {
  id: number;
  source_language: number | Language;
  target_language: number | Language;
  pair_code?: string | null;
  pricing_tier?: ('1' | '2' | '3') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: number;
  /**
   * Stable kebab-case identifier.
   */
  key: string;
  status?: ('draft' | 'published') | null;
  tier?: ('0' | '1' | '2') | null;
  slug: {
    ar: string;
    en: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  name: string;
  related_authorities?: (number | Authority)[] | null;
  top_documents?: (number | Document)[] | null;
  faqs?: (number | Faq)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use_cases".
 */
export interface UseCase {
  id: number;
  /**
   * Stable kebab-case identifier.
   */
  key: string;
  status?: ('draft' | 'published') | null;
  tier?: ('0' | '1' | '2') | null;
  slug: {
    ar: string;
    en: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  name: string;
  required_documents?: (number | Document)[] | null;
  related_authorities?: (number | Authority)[] | null;
  faqs?: (number | Faq)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  /**
   * Stable kebab-case identifier.
   */
  key: string;
  status?: ('draft' | 'published') | null;
  tier?: ('0' | '1' | '2') | null;
  slug: {
    ar: string;
    en: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  name: string;
  internal_only?: boolean | null;
  countries?: (number | Country)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market_profiles".
 */
export interface MarketProfile {
  id: number;
  country: number | Country;
  positioning?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  payment_methods?:
    | {
        method?: string | null;
        id?: string | null;
      }[]
    | null;
  support_hours?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jurisdiction_profiles".
 */
export interface JurisdictionProfile {
  id: number;
  country: number | Country;
  requirement_summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  certification_rule?: string | null;
  last_verified: string;
  source_references: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  top_authorities?: (number | Authority)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "administrative_areas".
 */
export interface AdministrativeArea {
  id: number;
  /**
   * Stable kebab-case identifier.
   */
  key: string;
  status?: ('draft' | 'published') | null;
  tier?: ('0' | '1' | '2') | null;
  slug: {
    ar: string;
    en: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  name: string;
  delivery_days?: string | null;
  courier_note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "combos".
 */
export interface Combo {
  id: number;
  document: number | Document;
  authority: number | Authority;
  status?: ('draft' | 'published') | null;
  unique_intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from_path: string;
  to_path: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'authorities';
        value: number | Authority;
      } | null)
    | ({
        relationTo: 'languages';
        value: number | Language;
      } | null)
    | ({
        relationTo: 'language_pairs';
        value: number | LanguagePair;
      } | null)
    | ({
        relationTo: 'price_books';
        value: number | PriceBook;
      } | null)
    | ({
        relationTo: 'use_cases';
        value: number | UseCase;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'market_profiles';
        value: number | MarketProfile;
      } | null)
    | ({
        relationTo: 'jurisdiction_profiles';
        value: number | JurisdictionProfile;
      } | null)
    | ({
        relationTo: 'administrative_areas';
        value: number | AdministrativeArea;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'combos';
        value: number | Combo;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  tier?: T;
  slug?:
    | T
    | {
        ar?: T;
        en?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  name?: T;
  summary?: T;
  body_sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  related_services?: T;
  faqs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  tier?: T;
  slug?:
    | T
    | {
        ar?: T;
        en?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  name?: T;
  category?: T;
  typical_pages?: T;
  requirements?: T;
  turnaround_hours?: T;
  related_authorities?: T;
  related_use_cases?: T;
  related_documents?: T;
  faqs?: T;
  combo_flags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authorities_select".
 */
export interface AuthoritiesSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  tier?: T;
  slug?:
    | T
    | {
        ar?: T;
        en?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  type?: T;
  name?: T;
  country?: T;
  languages?: T;
  requirement_summary?: T;
  required_language?: T;
  certification_rule?: T;
  legalization_required?: T;
  last_verified?: T;
  source_references?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  top_documents?: T;
  related_use_cases?: T;
  faqs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  tier?: T;
  slug?:
    | T
    | {
        ar?: T;
        en?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  name?: T;
  related_authorities?: T;
  top_documents?: T;
  faqs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "language_pairs_select".
 */
export interface LanguagePairsSelect<T extends boolean = true> {
  source_language?: T;
  target_language?: T;
  pair_code?: T;
  pricing_tier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price_books_select".
 */
export interface PriceBooksSelect<T extends boolean = true> {
  key?: T;
  currency?: T;
  base_pair?: T;
  per_page?: T;
  minimum_charge?: T;
  rush_per_page?: T;
  rush_promise_hours?: T;
  unit_words_per_page?: T;
  pair_overrides?:
    | T
    | {
        pair?: T;
        per_page?: T;
        rush_per_page?: T;
        id?: T;
      };
  addons?:
    | T
    | {
        label?: T;
        note?: T;
        id?: T;
      };
  b2b_note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use_cases_select".
 */
export interface UseCasesSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  tier?: T;
  slug?:
    | T
    | {
        ar?: T;
        en?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  name?: T;
  required_documents?: T;
  related_authorities?: T;
  faqs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  tier?: T;
  slug?:
    | T
    | {
        ar?: T;
        en?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  name?: T;
  internal_only?: T;
  countries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  tier?: T;
  slug?:
    | T
    | {
        ar?: T;
        en?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  name?: T;
  currency?: T;
  timezone?: T;
  price_book?: T;
  legal_notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market_profiles_select".
 */
export interface MarketProfilesSelect<T extends boolean = true> {
  country?: T;
  positioning?: T;
  payment_methods?:
    | T
    | {
        method?: T;
        id?: T;
      };
  support_hours?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jurisdiction_profiles_select".
 */
export interface JurisdictionProfilesSelect<T extends boolean = true> {
  country?: T;
  requirement_summary?: T;
  certification_rule?: T;
  last_verified?: T;
  source_references?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  top_authorities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "administrative_areas_select".
 */
export interface AdministrativeAreasSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  tier?: T;
  slug?:
    | T
    | {
        ar?: T;
        en?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  name?: T;
  delivery_days?: T;
  courier_note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  key?: T;
  question?: T;
  answer?: T;
  topics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "combos_select".
 */
export interface CombosSelect<T extends boolean = true> {
  document?: T;
  authority?: T;
  status?: T;
  unique_intro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from_path?: T;
  to_path?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  gtm_id?: string | null;
  ga4_id?: string | null;
  whatsapp_number?: string | null;
  whatsapp_link_pattern?: string | null;
  google_rating?: {
    value?: number | null;
    count?: number | null;
  };
  delivery?: {
    note_ar?: string | null;
    cairo_same_day?: boolean | null;
  };
  page_word_unit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  gtm_id?: T;
  ga4_id?: T;
  whatsapp_number?: T;
  whatsapp_link_pattern?: T;
  google_rating?:
    | T
    | {
        value?: T;
        count?: T;
      };
  delivery?:
    | T
    | {
        note_ar?: T;
        cairo_same_day?: T;
      };
  page_word_unit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
